<?php
module_load_include('inc', 'tp_mforms', 'tp_mforms.pages');
/**
 * @file
 * Module bootstrap file.
 */

/**
 * Implements hook_STORE_KEY_mforms_init().
 */
function tp_mforms_ajax_forms_mforms_init() {
  $store = MformsFormStateStore::getInstance('ajax_forms');
  $steps = MformsSteps::getInstance($store);
  $controls = MformsSimpleControls::getInstance($store, $steps);
  $controls->ajaxify();
  mforms_init_module('tp_mforms', 'ajax_forms', $store, $controls);
}

/**
 * Implements of hook_menu().
 *
 */
function tp_mforms_menu() {
  $items['mforms/ajax'] = array(
    'title' => 'Ajax forms',
    'page callback' => 'tp_mforms_ajax_forms_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'tp_mforms.pages.inc',
    'weight' => 1,
  );

  return $items;
}

function tp_mforms_theme($existing, $type, $theme, $path) {
// Ex 2: a custom form that comes from a custom module's "custom_donate_form()" function.
  $items['tp_mforms_ajax_form'] = array(
    'render element' => 'form',
    'template' => 'preference_form',
    'path' => drupal_get_path('theme', 'travelbooking') . '/templates/form',
  );

  return $items;
}
